from utils.utlis import eliminaColunaVazia, converteCsv, pegaSoNumero

from modelsTables.clientes import formataPlanilhaClientes
from modelsTables.produtos import formataPlanilhaProdutos
from modelsTables.servicos import formataPlanilhaServicos
from modelsTables.profissionais import formataPlanilhaProfissionais